name: hanzilens
description: Learn Chinese characters by taking photos.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI
  cupertino_icons: ^1.0.5
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.5
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dartz: ^0.10.1
  
  # Dependency Injection
  get_it: ^7.6.0
  injectable: ^2.1.2
  
  # Navigation
  auto_route: ^7.1.0
  
  # Network
  dio: ^5.1.2
  connectivity_plus: ^4.0.1
  
  # Local Storage
  shared_preferences: ^2.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite: ^2.2.8+4
  path_provider: ^2.0.15
  
  # Camera and Image
  camera: ^0.10.5+2
  image_picker: ^0.8.7+5
  image: ^4.0.17
  path: ^1.8.3
  
  # ML
  tflite_flutter: ^0.10.1
  
  # Utils
  permission_handler: ^10.2.0
  intl: ^0.18.1
  logger: ^1.3.0
  uuid: ^3.0.7
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
    
  # Dev Tools
  flutter_lints: ^2.0.1
  build_runner: ^2.4.4
  injectable_generator: ^2.1.6
  auto_route_generator: ^7.0.0
  hive_generator: ^2.0.0
  mockito: ^5.4.0
  bloc_test: ^9.1.3
  
flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/ml/
    
  fonts:
    - family: NotoSansSC
      fonts:
        - asset: assets/fonts/NotoSansSC-Regular.otf
        - asset: assets/fonts/NotoSansSC-Medium.otf
          weight: 500
        - asset: assets/fonts/NotoSansSC-Bold.otf
          weight: 700 